### ISSUE TITLE
About input file

### ISSUE THREAD

**Issue by SeanZhi** [hr1912/CYCLOPS#1]
What's the format of input file? Can you upload an example?

**Comment by hr1912** [comment]
I have added examples of input files. Please note that this script is based on the original CYCLOPS. Please ask the authors for their updated version.

**Comment by SeanZhi** [comment]
Thank you. The 'seed_example.txt' file looks like a gene list file.  It doesn't look the same as the gene list of "expr_example.txt". What's it used for?

**Comment by hr1912** [comment]
The expression file is the first 100 lines of multiple samples. The entire file has the over 25,000 genes. I did not upload the whole file for the size is very large. CYCLOPS used unsupervised method but require some seeds to start with. The seed gene list is the genes that are expected biologically to be cycling in a specific tissue. To run CYCLOPS properly, you should format your own expression file (gene as a row, sample as a column) and pick a list of genes that are expected to be cycling as seed. 
For more information, you should consult the original authors of CYCLOPS.
